name: sonar-check-workflow

on:
    push:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

    # JOB to run change detection
    changes:
        runs-on: ubuntu-latest
        steps:
            - name: test comment
              run: echo hello
